In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.DataFrame(
 {
  "class": ["A", "A", "A", "B", "C", "D"],
  "student_count": [42, 35, 42, 50, 47, 45],
  "all_pass": ["Yes", "Yes", "Yes", "No", "No", "Yes"],
 }
 )

In [10]:
df.drop_duplicates()

  class  student_count all_pass
0     A             42      Yes
1     A             35      Yes
3     B             50       No
4     C             47       No
5     D             45      Yes

In [11]:
df.drop_duplicates(["class", "student_count"])

  class  student_count all_pass
0     A             42      Yes
1     A             35      Yes
3     B             50       No
4     C             47       No
5     D             45      Yes

In [12]:
new_row = pd.DataFrame([["E", 51, True]],
columns=["class", "student_count", "all_pass"])

pd.concat([df, new_row])

  class  student_count all_pass
0     A             42      Yes
1     A             35      Yes
2     A             42      Yes
3     B             50       No
4     C             47       No
5     D             45      Yes
0     E             51     True

In [13]:
tips = pd.read_csv("tips.csv")

In [14]:
tips

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [15]:
tips_summed = tips.groupby(["sex", "smoker"])[["total_bill", "tip"]].sum()
tips_summed

               total_bill     tip
sex    smoker
Female No          977.68  149.77
       Yes         593.27   96.74
Male   No         1919.75  302.00
       Yes        1337.07  183.07

In [16]:
gb = tips.groupby("smoker")["total_bill"]
tips["adj_total_bill"] = tips["total_bill"] - gb.transform("mean")
tips

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,adj_total_bill
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,-2.198278
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,-8.848278
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1.821722
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,4.491722
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,5.401722
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,9.841722
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,6.423656
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,1.913656
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,-1.368278
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,-0.408278

In [17]:
gb = tips.groupby("smoker")["total_bill"]
gb

In [18]:
 tips.groupby(["sex", "smoker"]).first()

               total_bill   tip  day    time  size  price_per_person  \
sex    smoker
Female No           16.99  1.01  Sun  Dinner     2              8.49
       Yes           3.07  1.00  Sat  Dinner     1              3.07
Male   No           10.34  1.66  Sun  Dinner     3              3.45
       Yes          38.01  3.00  Sat  Dinner     4              9.50

                          Payer Name         CC Number Payment ID  \
sex    smoker
Female No         Christy Cunningham  3560325168603410    Sun2959
       Yes             Tiffany Brock  4359488526995267    Sat3455
Male   No             Douglas Tucker  4478071379779230    Sun4608
       Yes     James Christensen DDS   349793629453226    Sat8903

               adj_total_bill
sex    smoker
Female No           -2.198278
       Yes         -17.686344
Male   No           -8.848278
       Yes          17.253656

In [19]:
#164

In [20]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [21]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [22]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01  1.442801 -0.993872  0.506291 -0.565614
2013-01-02 -1.169178  1.271352  0.693886 -0.994058
2013-01-03 -1.131024 -0.006208  0.894359  0.672323
2013-01-04  1.137011 -0.633258  0.026289 -0.070149
2013-01-05 -1.112806  1.356688  0.633591  0.697709
2013-01-06  1.488442  1.371428  0.283752  1.153308

In [23]:
df2 = pd.DataFrame(
{
"A": 1.0,
"B": pd.Timestamp("20130102"),
"C": pd.Series(1, index=list(range(4)), dtype="float32"),
"D": np.array([3] * 4, dtype="int32"),
"E": pd.Categorical(["test", "train", "test", "train"]),
"F": "foo",
}
 )

In [24]:
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [25]:
#165