In [4]:
import pandas as pd
import numpy as np

In [5]:
tips = pd.read_csv("tips.csv")

In [6]:
tips

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [7]:
#89

In [8]:
tips[["total_bill", "tip", "smoker", "time"]]

     total_bill   tip smoker    time
0         16.99  1.01     No  Dinner
1         10.34  1.66     No  Dinner
2         21.01  3.50     No  Dinner
3         23.68  3.31     No  Dinner
4         24.59  3.61     No  Dinner
..          ...   ...    ...     ...
239       29.03  5.92     No  Dinner
240       27.18  2.00    Yes  Dinner
241       22.67  2.00    Yes  Dinner
242       17.82  1.75     No  Dinner
243       18.78  3.00     No  Dinner

[244 rows x 4 columns]

In [9]:
tips.assign(tip_rate=tips["tip"] / tips["total_bill"])

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_rate
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,0.059447
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,0.160542
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,0.166587
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,0.139780
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,0.146808
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,0.203927
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,0.073584
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,0.088222
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,0.098204
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,0.159744

In [10]:
tips[tips["total_bill"] > 10]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [11]:
is_dinner = tips["time"] == "Dinner"

In [12]:
is_dinner

0      True
1      True
2      True
3      True
4      True
       ...
239    True
240    True
241    True
242    True
243    True
Name: time, Length: 244, dtype: bool

In [13]:
is_dinner.value_counts()

True     176
False     68
Name: time, dtype: int64

In [14]:
tips[(tips["time"] == "Dinner") & (tips["tip"] > 5.00)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,503846761263,Sun2274
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4291280793094374,Sun6165
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
116,29.93,5.07,Male,No,Sun,Dinner,4,7.48,Shawn Blake,4689079711213722,Sun22
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4210875236164664,Sun9176
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
172,7.25,5.15,Male,Yes,Sun,Dinner,2,3.62,Larry White,30432617123103,Sun9209
181,23.33,5.65,Male,Yes,Sun,Dinner,2,11.66,Jason Cox,6556931703586223,Sun3402
183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,Dr. Michael James,4718501859162,Sun6059
211,25.89,5.16,Male,Yes,Sat,Dinner,4,6.47,Christopher Li,6011962464150569,Sat6735
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4922302538691962,Sat3374
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657

In [15]:
tips[(tips["size"] >= 5) | (tips["total_bill"] > 45)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
125,29.80,4.20,Female,No,Thur,Lunch,6,4.97,Angela Sanchez,503857080488,Thur3948
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4356531761046453,Thur3621
143,27.05,5.00,Female,No,Thur,Lunch,6,4.51,Regina Jones,4311048695487,Thur6179
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4210875236164664,Sun9176
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337
185,20.69,5.00,Male,No,Sun,Dinner,5,4.14,Joseph Howell,30362407455623,Sun5842
187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,David Barrett,4792882899700988,Sun9987
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
216,28.15,3.00,Male,Yes,Sat,Dinner,5,5.63,Shawn Barnett PhD,4590982568244,Sat7320

In [16]:
frame = pd.DataFrame(
    {"col1": ["A", "B", np.NaN, "C", "D"], "col2": ["F", np.NaN, "G", "H", "I"]}
)

In [17]:
frame

  col1 col2
0    A    F
1    B  NaN
2  NaN    G
3    C    H
4    D    I

In [18]:
frame[frame["col2"].isna()]

  col1 col2
1    B  NaN

In [19]:
frame[frame["col1"].notna()]

  col1 col2
0    A    F
1    B  NaN
3    C    H
4    D    I

In [20]:
tips.groupby("sex").size()

sex
Female     87
Male      157
dtype: int64

In [21]:
tips.groupby("sex").count()

,total_bill,tip,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
sex,,,,,,,,,,
Female,87,87,87,87,87,87,87,87,87,87
Male,157,157,157,157,157,157,157,157,157,157

In [22]:
tips.groupby("sex")["total_bill"].count()

sex
Female     87
Male      157
Name: total_bill, dtype: int64

In [23]:
tips.groupby("day").agg({"tip": np.mean, "day": np.size})

           tip  day
day
Fri   2.734737   19
Sat   2.993103   87
Sun   3.255132   76
Thur  2.771452   62

In [24]:
 tips.groupby(["smoker", "day"]).agg({"tip": [np.size, np.mean]})

             tip
            size      mean
smoker day
No     Fri     4  2.812500
       Sat    45  3.102889
       Sun    57  3.167895
       Thur   45  2.673778
Yes    Fri    15  2.714000
       Sat    42  2.875476
       Sun    19  3.516842
       Thur   17  3.030000

In [25]:
tips

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [26]:
df1 = pd.DataFrame({"key": ["A", "B", "C", "D"], "value": np.random.randn(4)})
df2 = pd.DataFrame({"key": ["B", "D", "D", "E"], "value": np.random.randn(4)})

In [27]:
pd.merge(df1, df2, on="key")

  key   value_x   value_y
0   B  1.212416 -0.539820
1   D -1.286706 -1.899865
2   D -1.286706  0.547446

In [28]:
indexed_df2 = df2.set_index("key")
pd.merge(df1, indexed_df2, left_on="key", right_index=True)

  key   value_x   value_y
1   B  1.212416 -0.539820
3   D -1.286706 -1.899865
3   D -1.286706  0.547446

In [29]:
 pd.merge(df1, df2, on="key", how="left")

  key   value_x   value_y
0   A -1.492135       NaN
1   B  1.212416 -0.539820
2   C  0.165648       NaN
3   D -1.286706 -1.899865
4   D -1.286706  0.547446

In [30]:
pd.merge(df1, df2, on="key", how="right")

  key   value_x   value_y
0   B  1.212416 -0.539820
1   D -1.286706 -1.899865
2   D -1.286706  0.547446
3   E       NaN  0.621602

In [31]:
#97

In [32]:
pd.merge(df1, df2, on="key", how="outer")

  key   value_x   value_y
0   A -1.492135       NaN
1   B  1.212416 -0.539820
2   C  0.165648       NaN
3   D -1.286706 -1.899865
4   D -1.286706  0.547446
5   E       NaN  0.621602

In [33]:
 df1 = pd.DataFrame(
 {"city": ["Chicago", "San Francisco", "New York City"], "rank": range(1, 4)}
)

df2 = pd.DataFrame(
{"city": ["Chicago", "Boston", "Los Angeles"], "rank": [1, 4, 5]}
 )

In [34]:
pd.concat([df1, df2])

            city  rank
0        Chicago     1
1  San Francisco     2
2  New York City     3
0        Chicago     1
1         Boston     4
2    Los Angeles     5

In [35]:
pd.concat([df1, df2]).drop_duplicates()

            city  rank
0        Chicago     1
1  San Francisco     2
2  New York City     3
1         Boston     4
2    Los Angeles     5

In [36]:
tips.head(10)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,Sun5985
7,26.88,3.12,Male,No,Sun,Dinner,4,6.72,Robert Buck,3514785077705092,Sun8157
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377,Sun6820
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3532124519049786,Sun3775

In [37]:
#100

In [38]:
tips.nlargest(10 + 5, columns="tip").tail(10)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,Dr. Michael James,4718501859162,Sun6059
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4922302538691962,Sat3374
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
88,24.71,5.85,Male,No,Thur,Lunch,2,12.36,Roger Taylor,4410248629955,Thur9003
181,23.33,5.65,Male,Yes,Sun,Dinner,2,11.66,Jason Cox,6556931703586223,Sun3402
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,503846761263,Sun2274
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4291280793094374,Sun6165
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6011787464177340,Thur7972
211,25.89,5.16,Male,Yes,Sat,Dinner,4,6.47,Christopher Li,6011962464150569,Sat6735

In [39]:
tips.nlargest(10, columns="tip").tail(10)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,Dr. Michael James,4718501859162,Sun6059
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4922302538691962,Sat3374
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
88,24.71,5.85,Male,No,Thur,Lunch,2,12.36,Roger Taylor,4410248629955,Thur9003

In [40]:
(
 tips.assign(
 rn=tips.sort_values(["total_bill"], ascending=False)
 .groupby(["day"])
 .cumcount()
 + 1
    )
     .query("rn < 3")
    .sort_values(["day", "rn"])
)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,rn
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,180026611638690,Fri9628,1
90,28.97,3.00,Male,Yes,Fri,Dinner,2,14.48,Daniel Mason,3597456900644078,Fri4175,2
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,1
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,2
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518,1
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337,2
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5544902205760175,Thur9313,1
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4356531761046453,Thur3621,2

In [41]:
(
tips.assign(
rnk=tips.groupby(["day"])["total_bill"].rank(
method="first", ascending=False
)
)
.query("rnk < 3")
.sort_values(["day", "rnk"])
)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,rnk
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,180026611638690,Fri9628,1.0
90,28.97,3.00,Male,Yes,Fri,Dinner,2,14.48,Daniel Mason,3597456900644078,Fri4175,2.0
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,1.0
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,2.0
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518,1.0
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337,2.0
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5544902205760175,Thur9313,1.0
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4356531761046453,Thur3621,2.0

In [42]:
tips.loc[tips["tip"] < 2, "tip"] *= 2
tips

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,2.02,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,3.32,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,3.50,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [43]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,2.02,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,3.32,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [44]:
tips = tips.loc[tips["tip"] <= 9]

In [45]:
tips

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,2.02,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,3.32,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,3.50,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [46]:
tips["total_bill"] = tips["total_bill"] - 2
tips["new_bill"] = tips["total_bill"] / 2

C:\Users\juanm\AppData\Local\Temp\ipykernel_15184\1729558012.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tips["total_bill"] = tips["total_bill"] - 2
C:\Users\juanm\AppData\Local\Temp\ipykernel_15184\1729558012.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tips["new_bill"] = tips["total_bill"] / 2

In [47]:
tips

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,new_bill
0,14.99,2.02,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,7.495
1,8.34,3.32,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,4.170
2,19.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,9.505
3,21.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,10.840
4,22.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,11.295
...,...,...,...,...,...,...,...,...,...,...,...,...
239,27.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,13.515
240,25.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,12.590
241,20.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,10.335
242,15.82,3.50,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,7.910
243,16.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,8.390

In [48]:
tips = tips.drop("new_bill", axis=1)

In [49]:
tips

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,14.99,2.02,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,8.34,3.32,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,19.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,21.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,22.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,27.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,25.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,20.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,15.82,3.50,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,16.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [50]:
tips[tips["total_bill"] > 10]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,14.99,2.02,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
2,19.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,21.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,22.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
5,23.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
...,...,...,...,...,...,...,...,...,...,...,...
239,27.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,25.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,20.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,15.82,3.50,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,16.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [51]:
#107

In [52]:
is_dinner = tips["time"] == "Dinner"
is_dinner

0      True
1      True
2      True
3      True
4      True
       ...
239    True
240    True
241    True
242    True
243    True
Name: time, Length: 243, dtype: bool

In [53]:
 is_dinner.value_counts()

True     175
False     68
Name: time, dtype: int64

In [54]:
tips["bucket"] = np.where(tips["total_bill"] < 10, "low", "high")
tips

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,bucket
0,14.99,2.02,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,high
1,8.34,3.32,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,low
2,19.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,high
3,21.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,high
4,22.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,high
...,...,...,...,...,...,...,...,...,...,...,...,...
239,27.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,high
240,25.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,high
241,20.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,high
242,15.82,3.50,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,high
243,16.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,high

In [55]:
tips["date1"] = pd.Timestamp("2013-01-15")
tips["date2"] = pd.Timestamp("2015-02-15")

In [56]:
tips["date1_year"] = tips["date1"].dt.year
tips["date2_month"] = tips["date2"].dt.month

In [57]:
tips["date1_next"] = tips["date1"] + pd.offsets.MonthBegin()
tips["months_between"] = tips["date2"].dt.to_period("M") - tips["date1"].dt.to_period("M")

In [58]:
tips[["date1", "date2", "date1_year", "date2_month", "date1_next", "months_between"]]

,date1,date2,date1_year,date2_month,date1_next,months_between
0,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
1,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
2,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
3,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
4,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
...,...,...,...,...,...,...
239,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
240,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
241,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
242,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
243,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>

In [59]:
 tips[["sex", "total_bill", "tip"]]

        sex  total_bill   tip
0    Female       14.99  2.02
1      Male        8.34  3.32
2      Male       19.01  3.50
3      Male       21.68  3.31
4    Female       22.59  3.61
..      ...         ...   ...
239    Male       27.03  5.92
240  Female       25.18  2.00
241    Male       20.67  2.00
242    Male       15.82  3.50
243  Female       16.78  3.00

[243 rows x 3 columns]

In [60]:
tips.drop("sex", axis=1)

,total_bill,tip,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,bucket,date1,date2,date1_year,date2_month,date1_next,months_between
0,14.99,2.02,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
1,8.34,3.32,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,low,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
2,19.01,3.50,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
3,21.68,3.31,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
4,22.59,3.61,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,27.03,5.92,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
240,25.18,2.00,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
241,20.67,2.00,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
242,15.82,3.50,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
243,16.78,3.00,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>

In [61]:
tips.rename(columns={"total_bill": "total_bill_2"})

,total_bill_2,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,bucket,date1,date2,date1_year,date2_month,date1_next,months_between
0,14.99,2.02,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
1,8.34,3.32,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,low,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
2,19.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
3,21.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
4,22.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,27.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
240,25.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
241,20.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
242,15.82,3.50,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
243,16.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>

In [62]:
tips = tips.sort_values(["sex", "total_bill"])
tips

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,bucket,date1,date2,date1_year,date2_month,date1_next,months_between
67,1.07,2.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455,low,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
92,3.75,2.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780,low,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
111,5.25,2.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801,low,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
145,6.35,3.00,Female,No,Thur,Lunch,2,4.18,Amy Young,4285454264477,Thur9331,low,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
135,6.51,2.50,Female,No,Thur,Lunch,2,4.26,Rebecca Harris,4320272020376174,Thur6600,low,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,39.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4356531761046453,Thur3621,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
182,43.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
156,46.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
59,46.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>
212,46.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,high,2013-01-15,2015-02-15,2013,2,2013-02-01,<25 * MonthEnds>

In [63]:
tips["time"].str.len()

67     6
92     6
111    6
145    5
135    5
      ..
142    5
182    6
156    6
59     6
212    6
Name: time, Length: 243, dtype: int64

In [64]:
tips["sex"].str.find("ale")

67     3
92     3
111    3
145    3
135    3
      ..
142    1
182    1
156    1
59     1
212    1
Name: sex, Length: 243, dtype: int64

In [65]:
firstlast = pd.DataFrame({"String": ["John Smith", "Jane Cook"]})
firstlast["First_Name"] = firstlast["String"].str.split(" ", expand=True)[0]
firstlast["Last_Name"] = firstlast["String"].str.rsplit(" ", expand=True)[1]
firstlast

       String First_Name Last_Name
0  John Smith       John     Smith
1   Jane Cook       Jane      Cook

In [66]:
firstlast = pd.DataFrame({"string": ["John Smith", "Jane Cook"]})
firstlast["upper"] = firstlast["string"].str.upper()
firstlast["lower"] = firstlast["string"].str.lower()
firstlast["title"] = firstlast["string"].str.title()
firstlast

       string       upper       lower       title
0  John Smith  JOHN SMITH  john smith  John Smith
1   Jane Cook   JANE COOK   jane cook   Jane Cook