In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("test.csv", index_col=0, header = 0)

In [3]:
df

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
User_ID,,,,,,,,,,
1000004,P00128942,M,46-50,7,B,2,1,1,11.0,NaN
1000009,P00113442,M,26-35,17,C,0,0,3,5.0,NaN
1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,NaN
1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,NaN
1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0
...,...,...,...,...,...,...,...,...,...,...
1006036,P00118942,F,26-35,15,B,4+,1,8,NaN,NaN
1006036,P00254642,F,26-35,15,B,4+,1,5,8.0,NaN
1006036,P00031842,F,26-35,15,B,4+,1,1,5.0,12.0
1006037,P00124742,F,46-50,1,C,4+,0,10,16.0,NaN
1006039,P00316642,F,46-50,0,B,4+,1,4,5.0,NaN

In [7]:
df = pd.read_csv("test.csv")

In [8]:
df

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
0,1000004,P00128942,M,46-50,7,B,2,1,1,11.0,NaN
1,1000009,P00113442,M,26-35,17,C,0,0,3,5.0,NaN
2,1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,NaN
3,1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,NaN
4,1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...
233594,1006036,P00118942,F,26-35,15,B,4+,1,8,NaN,NaN
233595,1006036,P00254642,F,26-35,15,B,4+,1,5,8.0,NaN
233596,1006036,P00031842,F,26-35,15,B,4+,1,1,5.0,12.0
233597,1006037,P00124742,F,46-50,1,C,4+,0,10,16.0,NaN
233598,1006039,P00316642,F,46-50,0,B,4+,1,4,5.0,NaN

In [9]:
df.describe()

,User_ID,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
count,2.335990e+05,233599.000000,233599.000000,233599.000000,161255.000000,71037.000000
mean,1.003029e+06,8.085407,0.410070,5.276542,9.849586,12.669454
std,1.726505e+03,6.521146,0.491847,3.736380,5.094943,4.125944
min,1.000001e+06,0.000000,0.000000,1.000000,2.000000,3.000000
25%,1.001527e+06,2.000000,0.000000,1.000000,5.000000,9.000000
50%,1.003070e+06,7.000000,0.000000,5.000000,9.000000,14.000000
75%,1.004477e+06,14.000000,1.000000,8.000000,15.000000,16.000000
max,1.006040e+06,20.000000,1.000000,18.000000,18.000000,18.000000

In [10]:
df = pd.read_csv("test.csv", index_col=0, header = 0)

In [11]:
df

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
User_ID,,,,,,,,,,
1000004,P00128942,M,46-50,7,B,2,1,1,11.0,NaN
1000009,P00113442,M,26-35,17,C,0,0,3,5.0,NaN
1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,NaN
1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,NaN
1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0
...,...,...,...,...,...,...,...,...,...,...
1006036,P00118942,F,26-35,15,B,4+,1,8,NaN,NaN
1006036,P00254642,F,26-35,15,B,4+,1,5,8.0,NaN
1006036,P00031842,F,26-35,15,B,4+,1,1,5.0,12.0
1006037,P00124742,F,46-50,1,C,4+,0,10,16.0,NaN
1006039,P00316642,F,46-50,0,B,4+,1,4,5.0,NaN

In [12]:
df.describe()

,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
count,233599.000000,233599.000000,233599.000000,161255.000000,71037.000000
mean,8.085407,0.410070,5.276542,9.849586,12.669454
std,6.521146,0.491847,3.736380,5.094943,4.125944
min,0.000000,0.000000,1.000000,2.000000,3.000000
25%,2.000000,0.000000,1.000000,5.000000,9.000000
50%,7.000000,0.000000,5.000000,9.000000,14.000000
75%,14.000000,1.000000,8.000000,15.000000,16.000000
max,20.000000,1.000000,18.000000,18.000000,18.000000

In [13]:
l = [12,9,8,]

s1= pd.Series(l)

print(s1)

0    12
1     9
2     8
dtype: int64

In [14]:
l = [12,9,8,]

s1= pd.Series(l, index =["a","b","c"])

print(s1)

a    12
b     9
c     8
dtype: int64

In [15]:
d = {"a":12,"b":13,"c":10}

s1= pd.Series(d)

print(s1)

a    12
b    13
c    10
dtype: int64

In [16]:
#Creating a dataframe
classes =  pd.Series(["Mathematics","Chemestry","Phsics","History","Geography","German"])

grades = pd.Series([90,54,77,22,25])

df1= pd.DataFrame({"Subjects": classes, "grades":grades})

In [17]:
df1

      Subjects  grades
0  Mathematics    90.0
1    Chemestry    54.0
2       Phsics    77.0
3      History    22.0
4    Geography    25.0
5       German     NaN

In [18]:
classes = ["Mathematics","Chemestry","Phsics","History","Geography","German"]

grades = [90,54,77,22,25]

df1= pd.DataFrame([classes, grades])

In [19]:
df1

             0          1       2        3          4       5
0  Mathematics  Chemestry  Phsics  History  Geography  German
1           90         54      77       22         25    None

In [20]:
df1.tail()

             0          1       2        3          4       5
0  Mathematics  Chemestry  Phsics  History  Geography  German
1           90         54      77       22         25    None

In [21]:
df = pd.read_csv("test.csv", index_col=0, header = 0)

In [22]:
df

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
User_ID,,,,,,,,,,
1000004,P00128942,M,46-50,7,B,2,1,1,11.0,NaN
1000009,P00113442,M,26-35,17,C,0,0,3,5.0,NaN
1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,NaN
1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,NaN
1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0
...,...,...,...,...,...,...,...,...,...,...
1006036,P00118942,F,26-35,15,B,4+,1,8,NaN,NaN
1006036,P00254642,F,26-35,15,B,4+,1,5,8.0,NaN
1006036,P00031842,F,26-35,15,B,4+,1,1,5.0,12.0
1006037,P00124742,F,46-50,1,C,4+,0,10,16.0,NaN
1006039,P00316642,F,46-50,0,B,4+,1,4,5.0,NaN

In [23]:
new_df = df.dropna()

In [24]:
new_df.describe()

,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
count,71037.000000,71037.000000,71037.000000,71037.000000,71037.000000
mean,8.219801,0.402002,2.725185,6.882287,12.669454
std,6.482756,0.490306,2.564070,4.510544,4.125944
min,0.000000,0.000000,1.000000,2.000000,3.000000
25%,3.000000,0.000000,1.000000,2.000000,9.000000
50%,7.000000,0.000000,1.000000,6.000000,14.000000
75%,14.000000,1.000000,4.000000,10.000000,16.000000
max,20.000000,1.000000,15.000000,16.000000,18.000000

In [25]:
df.describe()

,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
count,233599.000000,233599.000000,233599.000000,161255.000000,71037.000000
mean,8.085407,0.410070,5.276542,9.849586,12.669454
std,6.521146,0.491847,3.736380,5.094943,4.125944
min,0.000000,0.000000,1.000000,2.000000,3.000000
25%,2.000000,0.000000,1.000000,5.000000,9.000000
50%,7.000000,0.000000,5.000000,9.000000,14.000000
75%,14.000000,1.000000,8.000000,15.000000,16.000000
max,20.000000,1.000000,18.000000,18.000000,18.000000

In [26]:
new_df = df.fillna(0)

In [27]:
new_df.head()

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
User_ID,,,,,,,,,,
1000004,P00128942,M,46-50,7,B,2,1,1,11.0,0.0
1000009,P00113442,M,26-35,17,C,0,0,3,5.0,0.0
1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,0.0
1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,0.0
1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0

In [28]:
new_df.head()

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
User_ID,,,,,,,,,,
1000004,P00128942,M,46-50,7,B,2,1,1,11.0,0.0
1000009,P00113442,M,26-35,17,C,0,0,3,5.0,0.0
1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,0.0
1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,0.0
1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0

In [29]:
mean =  df["Product_Category_3"].mean()

In [30]:
new_df = df.fillna(mean)

In [31]:
new_df

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
User_ID,,,,,,,,,,
1000004,P00128942,M,46-50,7,B,2,1,1,11.000000,12.669454
1000009,P00113442,M,26-35,17,C,0,0,3,5.000000,12.669454
1000010,P00288442,F,36-45,1,B,4+,1,5,14.000000,12.669454
1000010,P00145342,F,36-45,1,B,4+,1,4,9.000000,12.669454
1000011,P00053842,F,26-35,1,C,1,0,4,5.000000,12.000000
...,...,...,...,...,...,...,...,...,...,...
1006036,P00118942,F,26-35,15,B,4+,1,8,12.669454,12.669454
1006036,P00254642,F,26-35,15,B,4+,1,5,8.000000,12.669454
1006036,P00031842,F,26-35,15,B,4+,1,1,5.000000,12.000000
1006037,P00124742,F,46-50,1,C,4+,0,10,16.000000,12.669454
1006039,P00316642,F,46-50,0,B,4+,1,4,5.000000,12.669454

In [32]:
median =  df["Product_Category_3"].median()

In [33]:
median

14.0

In [34]:
new_df = df.fillna(median)

In [35]:
new_df

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
User_ID,,,,,,,,,,
1000004,P00128942,M,46-50,7,B,2,1,1,11.0,14.0
1000009,P00113442,M,26-35,17,C,0,0,3,5.0,14.0
1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,14.0
1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,14.0
1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0
...,...,...,...,...,...,...,...,...,...,...
1006036,P00118942,F,26-35,15,B,4+,1,8,14.0,14.0
1006036,P00254642,F,26-35,15,B,4+,1,5,8.0,14.0
1006036,P00031842,F,26-35,15,B,4+,1,1,5.0,12.0
1006037,P00124742,F,46-50,1,C,4+,0,10,16.0,14.0
1006039,P00316642,F,46-50,0,B,4+,1,4,5.0,14.0

In [36]:
df.head()

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
User_ID,,,,,,,,,,
1000004,P00128942,M,46-50,7,B,2,1,1,11.0,NaN
1000009,P00113442,M,26-35,17,C,0,0,3,5.0,NaN
1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,NaN
1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,NaN
1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0

In [7]:
import numpy as np

In [8]:
df["Product_Category_3"].replace(np.nan, 0, inplace = True)
df["Product_Category_2"].replace(np.nan, 0, inplace = True)
df["Product_Category_1"].replace(np.nan, 0, inplace = True)

In [9]:
df["Stay_In_Current_City_Years"].replace('4+','4', inplace = True)

In [10]:
df

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
User_ID,,,,,,,,,,
1000004,P00128942,M,46-50,7,B,2,1,1,11.0,0.0
1000009,P00113442,M,26-35,17,C,0,0,3,5.0,0.0
1000010,P00288442,F,36-45,1,B,4,1,5,14.0,0.0
1000010,P00145342,F,36-45,1,B,4,1,4,9.0,0.0
1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0
...,...,...,...,...,...,...,...,...,...,...
1006036,P00118942,F,26-35,15,B,4,1,8,0.0,0.0
1006036,P00254642,F,26-35,15,B,4,1,5,8.0,0.0
1006036,P00031842,F,26-35,15,B,4,1,1,5.0,12.0
1006037,P00124742,F,46-50,1,C,4,0,10,16.0,0.0
1006039,P00316642,F,46-50,0,B,4,1,4,5.0,0.0

In [11]:
df["Age"].unique()

array(['46-50', '26-35', '36-45', '18-25', '51-55', '55+', '0-17'],
      dtype=object)

In [12]:
df["Age"].replace(['46-50', '26-35', '36-45', '18-25', '51-55', '55+', '0-17'],['50','35','45','25','55','60','17'], inplace = True)

In [13]:
df

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
User_ID,,,,,,,,,,
1000004,P00128942,M,50,7,B,2,1,1,11.0,0.0
1000009,P00113442,M,35,17,C,0,0,3,5.0,0.0
1000010,P00288442,F,45,1,B,4,1,5,14.0,0.0
1000010,P00145342,F,45,1,B,4,1,4,9.0,0.0
1000011,P00053842,F,35,1,C,1,0,4,5.0,12.0
...,...,...,...,...,...,...,...,...,...,...
1006036,P00118942,F,35,15,B,4,1,8,0.0,0.0
1006036,P00254642,F,35,15,B,4,1,5,8.0,0.0
1006036,P00031842,F,35,15,B,4,1,1,5.0,12.0
1006037,P00124742,F,50,1,C,4,0,10,16.0,0.0
1006039,P00316642,F,50,0,B,4,1,4,5.0,0.0

In [14]:
df.describe()

,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
count,233599.000000,233599.000000,233599.000000,233599.000000,233599.000000
mean,8.085407,0.410070,5.276542,6.799237,3.852756
std,6.521146,0.491847,3.736380,6.217668,6.256634
min,0.000000,0.000000,1.000000,0.000000,0.000000
25%,2.000000,0.000000,1.000000,0.000000,0.000000
50%,7.000000,0.000000,5.000000,5.000000,0.000000
75%,14.000000,1.000000,8.000000,14.000000,8.000000
max,20.000000,1.000000,18.000000,18.000000,18.000000

In [16]:
print(df.dtypes)

Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
dtype: object

In [17]:
pd.to_numeric(df['Age'])

User_ID
1000004    50
1000009    35
1000010    45
1000010    45
1000011    35
           ..
1006036    35
1006036    35
1006036    35
1006037    50
1006039    50
Name: Age, Length: 233599, dtype: int64

In [18]:
df["Age"] = df["Age"].astype('int')

In [19]:
print(df.dtypes)

Product_ID                     object
Gender                         object
Age                             int32
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
dtype: object

In [23]:
print(df.dtypes)

Product_ID                     object
Gender                         object
Age                             int32
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
dtype: object

In [5]:
df.drop_duplicates()

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
User_ID,,,,,,,,,,
1000004,P00128942,M,46-50,7,B,2,1,1,11.0,NaN
1000009,P00113442,M,26-35,17,C,0,0,3,5.0,NaN
1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,NaN
1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,NaN
1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0
...,...,...,...,...,...,...,...,...,...,...
1006036,P00118942,F,26-35,15,B,4+,1,8,NaN,NaN
1006036,P00254642,F,26-35,15,B,4+,1,5,8.0,NaN
1006036,P00031842,F,26-35,15,B,4+,1,1,5.0,12.0
1006037,P00124742,F,46-50,1,C,4+,0,10,16.0,NaN
1006039,P00316642,F,46-50,0,B,4+,1,4,5.0,NaN

In [7]:
df.drop_duplicates(subset=None, keep='first', inplace=True, ignore_index=False)

In [8]:
df

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
User_ID,,,,,,,,,,
1000004,P00128942,M,46-50,7,B,2,1,1,11.0,NaN
1000009,P00113442,M,26-35,17,C,0,0,3,5.0,NaN
1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,NaN
1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,NaN
1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0
...,...,...,...,...,...,...,...,...,...,...
1006036,P00118942,F,26-35,15,B,4+,1,8,NaN,NaN
1006036,P00254642,F,26-35,15,B,4+,1,5,8.0,NaN
1006036,P00031842,F,26-35,15,B,4+,1,1,5.0,12.0
1006037,P00124742,F,46-50,1,C,4+,0,10,16.0,NaN
1006039,P00316642,F,46-50,0,B,4+,1,4,5.0,NaN

In [4]:
df.corr()

,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
Occupation,1.000000,0.021872,-0.010465,-0.001685,0.003838
Marital_Status,0.021872,1.000000,0.018860,0.021766,0.016119
Product_Category_1,-0.010465,0.018860,1.000000,0.540063,0.225054
Product_Category_2,-0.001685,0.021766,0.540063,1.000000,0.543417
Product_Category_3,0.003838,0.016119,0.225054,0.543417,1.000000

In [5]:
def make_latin_square(n):
    return [[(i+j)%n+1 for i in range(n)] for j in range(n)]

In [6]:
make_latin_square(4)

[[1, 2, 3, 4], [2, 3, 4, 1], [3, 4, 1, 2], [4, 1, 2, 3]]

In [7]:
#Explicación:
#El usuario ingresa 5 como valor de n, y luego ingresa la lista de números 10 5 8 3 7. Después de eliminar los duplicados y ordenar la lista en orden ascendente, obtenemos la lista [3, 5, 7, 8, 10]. El segundo elemento más grande de esta lista es 8, que se imprime como resultado.

In [ ]:
n = int(input())
l = list(map(int,input().split()))

l = list(set(l))
l.sort()

print(l[-2])